# Generated by Django 3.1 on 2020-08-06 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarcSubscribersAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='activation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
