# Generated by Django 3.1 on 2020-08-06 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarcSubscribersAPI', '0003_auto_20200806_1507'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
