# Generated by Django 3.1 on 2020-08-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarcSubscribersAPI', '0005_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='token',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
