# Generated by Django 3.1 on 2020-08-06 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarcSubscribersAPI', '0006_subscriber_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='token',
        ),
    ]
