# Generated by Django 3.1 on 2020-08-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarcSubscribersAPI', '0007_remove_subscriber_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=60)),
            ],
        ),
    ]
