# Generated by Django 3.1 on 2020-08-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MarcSubscribersAPI', '0008_tokens'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tokens',
            new_name='Token',
        ),
    ]
